name: "Check migration files not modified"
on: [pull_request]

jobs:
  check-migration-files:
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Check migration files not modified
        run: make check-migration-files
